import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import { Montserrat, Figtree } from "next/font/google";

import type { TLayoutProps } from "@/lib/@types/root.types";
import { Navbar } from "@/components/shared/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster"
import { TooltipProvider } from "@/components/ui/tooltip";

// Styles for react-pdf package
import 'react-pdf/dist/Page/AnnotationLayer.css';
import 'react-pdf/dist/Page/TextLayer.css';

import "./globals.css";


// Font for application
const montserrat = Montserrat({ subsets: ["latin"] });


// Metadata for application
export const metadata: Metadata = {
  title: "flng !!",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: TLayoutProps) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <Navbar />
            {children}
          </TooltipProvider>
        </ThemeProvider>
        <Toaster />
        <Analytics />
      </body>
    </html>
  );
}
