import type { Metadata } from "next";
import { Montserrat as Inter } from "next/font/google";

import type { TLayoutProps } from "@/lib/@types/root.types";
import { Navbar } from "@/components/shared/navbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

import "./globals.css";


// Font for application
const inter = Inter({ subsets: ["latin"] });

// Metadata for application
export const metadata: Metadata = {
  title: "fling",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: TLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
