import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import { Montserrat } from "next/font/google";

import type { TLayoutProps } from "@/lib/@types/root.types";
import { supabaseClient } from "@/lib/supabase";
import { Navbar } from "@/components/shared/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ReduxProvider } from "@/components/providers/redux-provider";
import { PDFConfigProvider } from "@/components/providers/pdf-config-provider";

import "./globals.css";


// Font for application
const montserrat = Montserrat({ subsets: ["latin"] });


// Metadata for application
export const metadata: Metadata = {
  title: "flng !!",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: TLayoutProps) {
  // const { data } = supabaseClient.storage.from("storage").getPublicUrl("files/Resume.pdf");
  // console.log(data.publicUrl)

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <Navbar />
            <PDFConfigProvider>
              {children}
            </PDFConfigProvider>
          </ReduxProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
